services:
  ollama:
    container_name: ollama
    image: ollama/ollama:rocm
    image: docker.io/ollama/ollama:latest
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
            count: all
    volumes:
      - /storage_zfs/docker-volumes/ollama:/root/.ollama
    restart: always
